### ISSUE TITLE
node-cron库没有对setTimeout的延时做修正，可能导致累积误差过大，推荐使用cron库

### ISSUE THREAD

**Issue by sarahwang766** [cambridgejames/todo-manager#3]
https://github.com/cambridgejames/todo-manager/blob/48c047f4662666f9e256ca6e5ad4d95ce7453ab0/src/electron/cron/CronJobManager.ts#L1

node-cron库没有对setTimeout的延时做修正，可能导致累积误差过大，推荐使用cron库

node-cron没有做延时修正
![image](https://user-images.githubusercontent.com/51195467/223486171-4f1e9937-79c4-4d20-84da-99dcf3d26994.png)

cron在每次循环前会先修正误差
![image](https://user-images.githubusercontent.com/51195467/223487520-7603771a-6ed5-410b-b35a-24009a549d76.png)

**Comment by cambridgejames** [comment]
这么隐蔽的问题都被你发现了？不愧是你

**Comment by cambridgejames** [comment]
@sarahwang766 请修改

**Comment by sarahwang766** [comment]
已解决
