### ISSUE TITLE
Linux环境下，标题栏和菜单栏无法正确去除

### ISSUE THREAD

**Issue by sarahwang766** [cambridgejames/todo-manager#5]
![image](https://user-images.githubusercontent.com/51195467/224108414-05dc2428-8d27-4408-a706-43fe4bc5c218.png)

1. Linux下无法去除系统默认边框和标题栏，需要删除自定义标题栏和菜单栏
2. 删除菜单栏后，默认快捷键失效，需要重新注册全局快捷键

**Comment by cambridgejames** [comment]
请修改 @sarahwang766
